CREATE TABLE [agdevx].Roles
(
	[Id]                  UNIQUEIDENTIFIER	NOT NULL CONSTRAINT PK_Roles_Id PRIMARY KEY CLUSTERED DEFAULT NEWSEQUENTIALID(),
	[CreatedBy]			  UNIQUEIDENTIFIER	NOT NULL,
	[CreatedAt]			  DATETIME2(7)		NOT NULL CONSTRAINT DF_Roles_CreatedAt DEFAULT GETUTCDATE(),
	[ModifiedBy]	      UNIQUEIDENTIFIER	NOT NULL,
	[ModifiedAt]		  DATETIME2(7)		NOT NULL CONSTRAINT DF_Roles_ModifiedAt DEFAULT GETUTCDATE(),
	[IsActive]	          BIT				NOT NULL CONSTRAINT DF_Roles_IsActive DEFAULT 1,
	[IsDefault]			  BIT				NOT NULL CONSTRAINT DF_Roles_IsDefault DEFAULT 0,
	[Name]		          NVARCHAR(25)		NOT NULL CONSTRAINT UC_Roles_Name UNIQUE ([Name]),
	[Code]		          NVARCHAR(10)		NOT NULL CONSTRAINT UC_Roles_Code UNIQUE (Code),
	[Description]         NVARCHAR(200)		NOT NULL,

	CONSTRAINT CHK_Roles_Id CHECK (Id <> '00000000-0000-0000-0000-000000000000'),
	CONSTRAINT FK_Roles_Users_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES [agdevx].Users(Id),
	CONSTRAINT FK_Roles_Users_ModifiedBy FOREIGN KEY (ModifiedBy) REFERENCES [agdevx].Users(Id)
)
GO