CREATE TABLE [agdevx].UserRoles
(
	[Id]                  UNIQUEIDENTIFIER	NOT NULL CONSTRAINT PK_UserRoles_Id PRIMARY KEY CLUSTERED DEFAULT NEWSEQUENTIALID(),
	[CreatedBy]			  UNIQUEIDENTIFIER	NOT NULL,
	[CreatedAt]			  DATETIME2(7)		NOT NULL CONSTRAINT DF_UserRoles_CreatedAt DEFAULT GETUTCDATE(),
	[UserId]		      UNIQUEIDENTIFIER	NOT NULL,
	[RoleId]			  UNIQUEIDENTIFIER	NOT NULL,

	CONSTRAINT CHK_UserRoles_Id CHECK (Id <> '00000000-0000-0000-0000-000000000000'),
	CONSTRAINT FK_UserRoles_Users_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES [agdevx].Users(Id),
	CONSTRAINT FK_UserRoles_Users_UserId FOREIGN KEY (UserId) REFERENCES [agdevx].Users(Id),
	CONSTRAINT FK_UserRoles_Roles_RoleId FOREIGN KEY (RoleId) REFERENCES [agdevx].Roles(Id),
	CONSTRAINT UC_UserRoles_UserId_RoleId UNIQUE (UserId, RoleId)
)
GO